### ISSUE TITLE
Error when factor variables are included

### ISSUE THREAD

**Issue by oofd** [beckyfisher/FSSgam#4]
Hi, thanks for your code. I'm trying out this method in my analysis, however an error is coming up when I specify factor variables in `full.subsets.gam()`

This is the error:
> Error in sort.list(y) : 'x' must be atomic for 'sort.list'
> Have you called 'sort' on a list? 

Seems to coming out from a `sort` function

The function runs if I don't specify factors.

**Comment by oofd** [comment]
So I've found out what the problem was... I gave a class tibble type dataframe to `full.subsets.gam()` which caused the error at line 157 of the `full.subsets.gam()` function. It worked once I just gave it a pure dataframe.

**Comment by TimLanglois** [comment]
Thanks Dahlia,

I've also encountered this issue and found the same fix.

Becky – would it be sensible to coerce dat to as.data.frame() in the function?

Cheers
Tim

Dr Tim Langlois
Lecturer
Marine Ecology Group<https://uwamegfisheries.github.io/> | The UWA Oceans Institute & School of Biological Sciences

M: 0423 708 312 | E: timothy.langlois@uwa.edu.au<mailto:timothy.langlois@uwa.edu.au>
P<https://scholar.google.com.au/citations?user=jEiHZ0cAAAAJ>ublications<https://scholar.google.com.au/citations?user=jEiHZ0cAAAAJ>
Facebook<https://www.facebook.com/marineecologygroupUWA?fref=ts>
YouTube<https://www.youtube.com/channel/UCZJl1AUIa-O6WgTSgViNeew>
GitHub<https://github.com/TimLanglois>
<applewebdata://2F8F787C-E9AF-47C1-8006-005525C21D26/appear.in/tim.langlois>appear.in<https://appear.in/tim.langlois>
[http://static.weboffice.uwa.edu.au/visualid/graphics/email/uwa-crest-sig.gif]<http://www.uwa.edu.au/>
