### ISSUE TITLE
P-values of predictors?

### ISSUE THREAD

**Issue by chenyj8** [beckyfisher/FSSgam#8]
In addition to the relative importance of predictors, is it possible to get their P-values?

**Comment by beckyfisher** [comment]
Hi Chenyj8,
the relative importance score is a sum of the weights for all models in which the predictor is present. The p-value for a given predictor will be different within each of those models, so no - it is not possible to provide that across the whole model set. It is possible to extract the p value for predictors in a given model as presented in the underlying gam(m4) output. I have seen this presented from time to time, particularly if their is a clear "top" model according to AICc. Please see the help files for gam, gamm (mgcv) or gamm4 (gamm4) for more information for how those p-values are calculated, as they are nothing to do with the FSSgam package.
