### ISSUE TITLE
Error on ### now fit the models

### ISSUE THREAD

**Issue by lydeejeanne** [beckyfisher/FSSgam#9]
I'm trying to make a tutorial based on this data and can't seem to troubleshoot why I'm getting this error for the code following ### now fit the models --------------------------------------------------------- 
Any assistance appreciated 

Error in names(dat) <- object$term : 
  'names' attribute [1] must be the same length as the vector [0]

**Comment by lydeejeanne** [comment]
I think I figured it out, just needed to add the following to get it to work:

dat$site=as.factor(dat$site)

Thanks for providing this tutorial!

**Comment by beckyfisher** [comment]
Glad you worked it out lydeejeanne!
